version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build:
      context: ./django/coolsite
      dockerfile: Dockerfile
    command: gunicorn coolsite.wsgi:application --bind 0.0.0.0:8000
    working_dir: /code
    volumes:
      - ./django/coolsite:/code            
      - static_volume:/code/staticfiles     
      - media_volume:/code/media            
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
      - static_volume:/staticfiles                   
      - media_volume:/media                          
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
