services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build:
      context: ./django/coolsite
      dockerfile: Dockerfile
    command: gunicorn coolsite.wsgi:application --bind 0.0.0.0:8000
    working_dir: /code
    volumes:
      - ./django/coolsite:/code            
      - static_volume:/code/staticfiles     
      - media_volume:/code/media            
    env_file:
      - .env
    depends_on:
      - db
      - mysql
      - redis

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
      - static_volume:/staticfiles                   
      - media_volume:/media                          
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
  mysqldata:
