# Generated by Django 5.2.3 on 2025-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
